extends: 'eslint:recommended'
env:
  es6: true
  browser: true
  mocha: true
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    globalReturn: false
    impliedStrict: true
    jsx: false
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
  no-unused-vars:
    - error
    -
      vars: all
      args: none
      ignoreRestSiblings: false
  globals:
    globals: true